### ISSUE TITLE
DI0000 - Question to AJ work group

### ISSUE THREAD

**Issue by sheagraffo** [christhompson17/EIDSS#4]
Hello, @aatmnv 

Yadda yadda
![10339 civil registry](https://cloud.githubusercontent.com/assets/26907736/25287539/c5142fbc-268f-11e7-8e1f-95f8c35209c2.jpg)

  #[google.com](url)

**Comment by sheagraffo** [comment]
Here's my next comments.

**Comment by sheagraffo** [comment]
This is my third comment on my own issue.

**Comment by aatmnv** [comment]
Here is a comment back to your third comment. How does it look?

**Comment by aatmnv** [comment]
Let me try to use button "Close and Comment" now. This is the last and the final, I hope, comment on this Georgian issue.

**Comment by sheagraffo** [comment]
@aatmnv 

Great.  Did the @aatmnv generate a notification as well?

**Comment by aatmnv** [comment]
No I didn't get any notifications.

**Comment by sheagraffo** [comment]
I'm getting an email with your comment every time you comment.  are you?

**Comment by christhompson17** [comment]
I'm getting emails for every action in this thread, but that is because it was assigned to me, I think.
